# Generated by Django 3.0.6 on 2020-05-31 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active_period',
            name='end_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='active_period',
            name='start_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='active_period',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_log.users'),
        ),
    ]
