# Generated by Django 3.0.6 on 2020-05-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_log', '0002_auto_20200531_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active_period',
            name='user_id',
            field=models.CharField(max_length=20),
        ),
    ]
